## FEATURE ENCODING METHODS

Feature Encoding converts categorical data into numerical form

## LABEL ENCODING

LABEL ENCODING assign a unique number to each category 

# EXAMPLE

 - RED--> 0
 - BLUE--> 1
 - GREEN--> 2

IT IS SUITABLE FOR ORDINAL CATEGORIES

In [3]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [ ]:

colors=['red','blue','green','red']

le=LabelEncoder()
print(le.fit_transform(colors))

[2 0 1 2]

## ONE HOT ENCODING

ONE-HOT ENCODING CREATES A SEPARATE BINARY COLUMN FOR EACH CATGORY

EXAMPLE



COLOUR          RED     BLUE     GREEN


RED             1       0         0


BLUE            0       1         0

In [5]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [6]:
colors=['red','blue','green','red']


df=pd.DataFrame({'colors':colors})

In [7]:
print(pd.get_dummies(df))

   colors_blue  colors_green  colors_red
0        False         False        True
1         True         False       False
2        False          True       False
3        False         False        True

### method 2

In [1]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import pandas as pd

In [2]:
colors=['red','blue','green','red']

In [3]:
#label encoding

le=LabelEncoder()
print(le.fit_transform(colors))

[2 0 1 2]

In [5]:
#one-hot encoding

df=pd.DataFrame({'color':colors})
df

   color
0    red
1   blue
2  green
3    red

In [9]:
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(df)
print(pd.DataFrame(encoded))

     0    1    2
0  0.0  0.0  1.0
1  1.0  0.0  0.0
2  0.0  1.0  0.0
3  0.0  0.0  1.0

## TASK1

In [11]:
fruits=['apple','banana','orange','apple']
fruits

['apple', 'banana', 'orange', 'apple']

In [13]:
le1=LabelEncoder()
print(le1.fit_transform(fruits))

[0 1 2 0]

In [18]:
df1=pd.DataFrame({'fruit':fruits})
df1

    fruit
0   apple
1  banana
2  orange
3   apple

#onehot encoding

In [19]:
encoder1=OneHotEncoder(sparse_output=False)
encoded1=(encoder1.fit_transform(df1))

In [20]:
print(pd.DataFrame(encoded1))

     0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0

## task2

In [23]:
cities=(['delhi','mumbai','chennai','delhi'])
cities

['delhi', 'mumbai', 'chennai', 'delhi']

In [24]:
le2=LabelEncoder()
print(le2.fit_transform(cities))

[1 2 0 1]

In [25]:
#onehot encoding

df2=pd.DataFrame({'city':cities})
df2

      city
0    delhi
1   mumbai
2  chennai
3    delhi

In [26]:
encoder2=OneHotEncoder(sparse_output=False)
encoded2=(encoder2.fit_transform(df2))

In [27]:
print(pd.DataFrame(encoded2))

     0    1    2
0  0.0  1.0  0.0
1  0.0  0.0  1.0
2  1.0  0.0  0.0
3  0.0  1.0  0.0