In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\adith\appdata\local\programs\python\python314\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\adith\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adith\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\adith\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\adith\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [2]:
import numpy as np

PANDAS SERIES

In [5]:
#SERIES= HOMOGENEUS AND 1D
#DATAFRAME=HETROGENIUS AND 2D

In [6]:
series_data=np.array([1,3,4,5,6])
pd.Series(series_data)

0    1
1    3
2    4
3    5
4    6
dtype: int64

In [7]:
sd=np.array([1,3,4,5,6.5])
pd.Series(sd)

0    1.0
1    3.0
2    4.0
3    5.0
4    6.5
dtype: float64

DATA FRAME

In [8]:
data={'id':[101,102,103,104,105],
      'name':['sam','jhon','alan','kate','joy'],
      'age':[15,16,17,18,19],
      'mark':[25,35,45,55,65]}

dataframe1=pd.DataFrame(data)
dataframe1

    id  name  age  mark
0  101   sam   15    25
1  102  jhon   16    35
2  103  alan   17    45
3  104  kate   18    55
4  105   joy   19    65

DATA FRAME USING TUPLE list

In [9]:
data_tuple=[(101,"sam",15,55),
            (102,"joy",16,45),
            (103,"jhon",16,65),
            (104,"kate",18,75),
            (105,"alan",19,85)]

dataframe=pd.DataFrame(data_tuple,columns=['id','name','age','mark'])
dataframe

    id  name  age  mark
0  101   sam   15    55
1  102   joy   16    45
2  103  jhon   16    65
3  104  kate   18    75
4  105  alan   19    85

DATA FRME USING LIST OF DICTINORIES

In [10]:
data_list=[{'id':101,'name':"joy",'age':16,'mark':55},
          {'id':102,'name':"jhon",'age':17,'mark':45},
{'id':103,'name':"jame",'age':10,'mark':65},
{'id':104,'name':"kate",'age':11,'mark':85},
{'id':105,'name':"alan",'age':19,'mark':95}]

dataframe3=pd.DataFrame(data_list)
dataframe3

    id  name  age  mark
0  101   joy   16    55
1  102  jhon   17    45
2  103  jame   10    65
3  104  kate   11    85
4  105  alan   19    95

reading CSV file

In [11]:
data=pd.read_csv("C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv")
data

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

cleaning

In [ ]:
d=pd.read_csv(r"C:\Users\adith\python practice\numpy\stock_data_pandas.csv")
d

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA             -1       -1  n.a.     ratan tata

In [ ]:
#SKIP ROWS-SKIP THE SPECIFIED NUMBER OF ROWS FROM THE BEGINING INCLUDING THE HEADDER ROW
data=pd.read_csv(r"C:\Users\adith\python practice\numpy\stock_data_pandas.csv",skiprows=2)
data

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1   RIL  not available   50  1023  mukesh ambani
2  TATA             -1   -1  n.a.     ratan tata

In [14]:
data=pd.read_csv(r"C:\Users\adith\python practice\numpy\stock_data_pandas.csv",header=3)
data

   MSFT             -1  85    64     bill gates
0   RIL  not available  50  1023  mukesh ambani
1  TATA             -1  -1  n.a.     ratan tata

In [15]:
data=pd.read_csv(r"C:\Users\adith\python practice\numpy\stock_data_pandas.csv",header=None)
data

         0              1        2      3              4
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA             -1       -1   n.a.     ratan tata

In [ ]:
#SET NEW NAMES TO COLUMN

data=pd.read_csv(r"C:\Users\adith\python practice\numpy\stock_data_pandas.csv",header=None,names=["a","b","c","d","e"])
data

data.shape
data.head() #first 5 values
data.head(3)
data.tail() #last 5 values
data.tail(2)
data.columns #name of header

data.b #to get specific column
data['d']
data[['a','d']]  # gto get multiple colums

         a              b        c      d              e
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani

In [17]:
#SELECT ONLY THE FIRST N ROWS FROM DATAFRAME

data=pd.read_csv(r"C:\Users\adith\python practice\numpy\stock_data_pandas.csv",nrows=3)
data

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [10]:
data_list=[{'id':101,'name':"joy",'age':16,'mark':55},
          {'id':102,'name':"jhon",'age':17,'mark':45},
{'id':103,'name':"jame",'age':10,'mark':65},
{'id':104,'name':"kate",'age':11,'mark':85},
{'id':105,'name':"alan",'age':19,'mark':95}]

df=pd.DataFrame(data_list)
df
new_data=df.copy()
place=['kerala','delhi','UP','AP','RAJASTHAN']
new_data['place']=place
new_data

    id  name  age  mark      place
0  101   joy   16    55     kerala
1  102  jhon   17    45      delhi
2  103  jame   10    65         UP
3  104  kate   11    85         AP
4  105  alan   19    95  RAJASTHAN

#deleting a specific column

In [12]:
#deleting a specific column
new_data=new_data.drop('age',axis=1)  #column
new_data

    id  name  mark      place
0  101   joy    55     kerala
1  102  jhon    45      delhi
2  103  jame    65         UP
3  104  kate    85         AP
4  105  alan    95  RAJASTHAN

ASCENDING AND DESENDING

In [20]:
data_list=[{'id':101,'name':"joy",'age':16,'mark':55},
          {'id':102,'name':"jhon",'age':17,'mark':45},
{'id':103,'name':"jame",'age':10,'mark':65},
{'id':104,'name':"kate",'age':11,'mark':85},
{'id':105,'name':"alan",'age':19,'mark':95}]

df=pd.DataFrame(data_list)
df

df.sort_values('age')  #asending

df.sort_values('age',ascending=False)  #desending order

df.index

data=df.set_index('id')  #to set index number as id
data

data1=df.reset_index() #to rest index number
data1

   index   id  name  age  mark
0      0  101   joy   16    55
1      1  102  jhon   17    45
2      2  103  jame   10    65
3      3  104  kate   11    85
4      4  105  alan   19    95

In [15]:
data_list=[{'id':101,'name':"joy",'age':16,'mark':55},
          {'id':102,'name':"jhon",'age':17,'mark':45},
{'id':103,'name':"jame",'age':10,'mark':65},
{'id':104,'name':"kate",'age':11,'mark':85},
{'id':105,'name':"alan",'age':19,'mark':95}]

data_list

dataframe=pd.DataFrame(data_list)
dataframe

dataframe.loc[3]   #to acesss row 


dataframe.loc[dataframe.name=='jame']

dataframe.set_index('name')
dataframe

    id  name  age  mark
0  101   joy   16    55
1  102  jhon   17    45
2  103  jame   10    65
3  104  kate   11    85
4  105  alan   19    95

In [22]:
data_list=[{'id':101,'name':"joy",'age':16,'mark':55},
          {'id':102,'name':"jhon",'age':17,'mark':45},
{'id':103,'name':"jame",'age':10,'mark':65},
{'id':104,'name':"kate",'age':11,'mark':85},
{'id':105,'name':"alan",'age':19,'mark':95}]
data_list

dat=pd.DataFrame(data_list)
dat

a=dat.set_index('name')
a

a.loc['joy']

dat.iloc[4]  #integer index only

dat.iloc[[0,3,4]]  #to get acess number of elemnts

dat.dtypes

id      int64
name      str
age     int64
mark    int64
dtype: object

In [16]:
data=pd.read_csv("C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv")
data

data.shape

data.size

data.columns

data.dtypes

data.sort_values('temperature')

dat=data.copy()
dat.drop('day',axis=1)   #column

   temperature  windspeed  event
0           32          6   Rain
1           35          7  Sunny
2           28          2   Snow
3           24          7   Snow
4           32          4   Rain
5           31          2  Sunny

In [ ]:
data=pd.read_csv("C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv")
data

data.sort_values('temperature') #default-acending

          day  temperature  windspeed  event
3  01-04-2017           24          7   Snow
2  01-03-2017           28          2   Snow
5  01-06-2017           31          2  Sunny
0  01-01-2017           32          6   Rain
4  01-05-2017           32          4   Rain
1  01-02-2017           35          7  Sunny

In [25]:
data=pd.read_csv("C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv")
data

data.event.unique()

#OR

data['event'].unique()


data.event.value_counts()

event
Rain     2
Sunny    2
Snow     2
Name: count, dtype: int64

#SLICING

In [ ]:
data=pd.read_csv("C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv")
data

data[::]
data[1:3]

data[['day','temperature']][1:3]

data.temperature.max()
#OR
data['temperature'].max()

data.temperature.min()
#OR
data['temperature'].min()


data.temperature.mean()

np.int64(24)

In [27]:
data=pd.read_csv("C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv")
data

data.describe()  #to get statiscal summary of the data

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

conditional selecting

In [28]:
data=pd.read_csv("C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv")
data

data[data['temperature']>30]  

data['event'][data.temperature==data.temperature.min()]

3    Snow
Name: event, dtype: str

Handling missing data

In [29]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data_missing_pandas.csv')
data

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork          NaN          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai          NaN          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [ ]:
#checking missing values

data.isna()

data.isna().sum()
#OR
data.isnull().sum()

dat=data.fillna(0) #fill missing value with zero
dat


avg=data['temperature'].mean()
data.fillna(avg)     #fillimg with avg

day            0
temperature    0
windspeed      0
event          0
dtype: int64

In [24]:
data.ffill()  #forwardfill

data.bfill()  #backward fill

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

LINEAR INTERPPOLATION

#Tecnique used to estimate missing values

In [ ]:
df=pd.DataFrame({
    'a':[1,2,np.nan,4],
    'b':[5,np.nan,np.nan,8],
    'c':[9,10,11,12] ,
    'd':[2,4,np.nan,8]      
})
df.interpolate()

     a    b   c    d
0  1.0  5.0   9  2.0
1  2.0  6.0  10  4.0
2  3.0  7.0  11  6.0
3  4.0  8.0  12  8.0

In [33]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data_missing_pandas.csv')
data

data['temperature']=pd.to_numeric(data['temperature'])
data['temperature']=data['temperature'].interpolate()
data

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork         30.0          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai         66.0          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [34]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data_missing_pandas.csv')
data

data=data.dropna()
data   #TO DROP ROWS HAVING NULL VALUE

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [35]:
data=data.dropna(how='all')
data
   #ROW HAVING ALL NULL VALUES DELETE TEH ROW

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [25]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data_missing_pandas.csv')
data

data=data.dropna(how='any')
data    #to delete a row with having one null value

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [ ]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\Example1_pandas.csv')
data

data.shape

data.size

data.columns

data.dtypes

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female   NaN
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female   NaN
6  107       Joey   NewYork    Male  30.0
7  108      Hessa       NaN  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male   NaN

In [ ]:
data.sort_values('Age')

    ID       Name     Place  Gender   Age
7  108      Hessa       NaN  Female  21.0
2  103      Elena    London  Female  22.0
0  101       Jaya    London  Female  23.0
3  104  Katherine   NewYork  Female  25.0
8  109       Ayan     Saudi    Male  29.0
6  107       Joey   NewYork    Male  30.0
4  105      Damon  Virginia    Male  45.0
1  102      Jeena   NewYork  Female   NaN
5  106     Bonnie   Georgia  Female   NaN
9  110       Robb       NaN    Male   NaN

In [36]:

data=data.copy()
data.drop('ID',axis=1)

        Name     Place  Gender   Age
0       Jaya    London  Female  23.0
1      Jeena   NewYork  Female   NaN
2      Elena    London  Female  22.0
3  Katherine   NewYork  Female  25.0
4      Damon  Virginia    Male  45.0
5     Bonnie   Georgia  Female   NaN
6       Joey   NewYork    Male  30.0
7      Hessa       NaN  Female  21.0
8       Ayan     Saudi    Male  29.0
9       Robb       NaN    Male   NaN

In [37]:
data.describe()

              ID        Age
count   10.00000   7.000000
mean   105.50000  27.857143
std      3.02765   8.295151
min    101.00000  21.000000
25%    103.25000  22.500000
50%    105.50000  25.000000
75%    107.75000  29.500000
max    110.00000  45.000000

In [8]:

data.isna()

data.isna().sum()
#OR
data.isnull().sum()

dat=data.fillna(0) 
dat


avg=data['Age'].mean()
data.fillna(avg)

    ID       Name      Place  Gender        Age
0  101       Jaya     London  Female  23.000000
1  102      Jeena    NewYork  Female  27.857143
2  103      Elena     London  Female  22.000000
3  104  Katherine    NewYork  Female  25.000000
4  105      Damon   Virginia    Male  45.000000
5  106     Bonnie    Georgia  Female  27.857143
6  107       Joey    NewYork    Male  30.000000
7  108      Hessa  27.857143  Female  21.000000
8  109       Ayan      Saudi    Male  29.000000
9  110       Robb  27.857143    Male  27.857143

In [ ]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\missing_weather_data_pandas.csv')
data

         day temperature windspeed   event
0   1/1/2017        32 F     6 mph    Rain
1   1/4/2017      -99999         9   Sunny
2   1/5/2017          28    -99999    Snow
3   1/6/2017      -99999         7       0
4   1/7/2017        32 C    -88888    Rain
5   1/8/2017        38 F    -99999   Sunny
6   1/9/2017          35   10 kmph       0
7  1/10/2017          34         8  Cloudy
8  1/11/2017          40        12   Sunny

Here, we replace occurrence of alphabets (both upper and lower) in the 'temperature' column with an empty string.

Replace any occurrence of alphabets in the "windspeed' column with an empty string.

Replace any occurrence of alphabets in the 'event' column with an empty string.

The replace() method will remove all alphabetic character from the specified columns.

regex=True This parameter indicates that the replacement values are specified using regular expression.

This means that instead of exact string matches, pandas will look for patterns that match the specified values.

In [ ]:


data.replace('-99999',np.nan)


data.replace({'temperature':['-99999','40'],'windspeed':'-88888','event':'0'},np.nan)


data.replace({'-99999':np.nan,'-88888':np.nan,'0':'rain'})


data.replace({'temperature':'[A-Za-z]','windpeed':'[A-Za-z]','event':'[A-Za-z]'},'',regex=True)


data.replace(['Rain','Sunny','Cloudy','Snow'],[100,101,102,103])

         day temperature windspeed event
0   1/1/2017        32 F     6 mph   100
1   1/4/2017      -99999         9   101
2   1/5/2017          28    -99999   103
3   1/6/2017      -99999         7     0
4   1/7/2017        32 C    -88888   100
5   1/8/2017        38 F    -99999   101
6   1/9/2017          35   10 kmph     0
7  1/10/2017          34         8   102
8  1/11/2017          40        12   101

PARSING DATES

In [23]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv')
data

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

In [ ]:
data.dtypes


data1=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv',parse_dates=['day'])
data1

data1.dtypes

type(data1['day'][0])

data2=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data_pandas.csv',parse_dates=['day'],index_col='day')
data2


ind=pd.date_range('2018-01-01',"2018-05-11")
ind

type(ind[0])


str='20-09-2025'
obj=pd.to_datetime(str)    #string to date and time format
obj


y=pd.to_datetime('01/12/17',yearfirst=True)
y   #to change date as  year {position change}

C:\Users\adith\AppData\Local\Temp\ipykernel_2552\4028986627.py:22: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  obj=pd.to_datetime(str)    #string to date and time format

Timestamp('2001-12-17 00:00:00')

#GROUP BY

creates sub dataframes based on a single column value or a combination of multiple column value.
when you apply groupby to a categorical column in a dataframe, it returns a Groupßy object.
This object allows you to perform various operations on the grouped data.

In [8]:
data11=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data .csv')
data11

           day     city  temperature  windspeed   event
0   01-01-2017  newyork           32          6    Rain
1   01-04-2017  newyork           36          7   Sunny
2   01-05-2017  newyork           28         12    Snow
3   01-06-2017  newyork           33          7   Sunny
4   01-07-2017   mumbai           90          5   Sunny
5   01-08-2017   mumbai           85         12     Fog
6   01-09-2017   mumbai           87         15     Fog
7   01-10-2017   mumbai           92          5    Rain
8   01-11-2017    paris           45         20   Sunny
9   01-12-2017    paris           50         13  Cloudy
10  01-13-2017    paris           54          8  Cloudy
11  01-14-2017    paris           42         10  Cloudy

In [11]:
gr=data11.groupby('city')
gr

gr.apply(display)

          day  temperature  windspeed  event
4  01-07-2017           90          5  Sunny
5  01-08-2017           85         12    Fog
6  01-09-2017           87         15    Fog
7  01-10-2017           92          5   Rain

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-04-2017           36          7  Sunny
2  01-05-2017           28         12   Snow
3  01-06-2017           33          7  Sunny

           day  temperature  windspeed   event
8   01-11-2017           45         20   Sunny
9   01-12-2017           50         13  Cloudy
10  01-13-2017           54          8  Cloudy
11  01-14-2017           42         10  Cloudy

Empty DataFrame
Columns: [day, temperature, windspeed, event]
Index: []

In [12]:
for city,group in gr:
    print('Group:',city) 
    display(group)

Group: mumbai

          day    city  temperature  windspeed  event
4  01-07-2017  mumbai           90          5  Sunny
5  01-08-2017  mumbai           85         12    Fog
6  01-09-2017  mumbai           87         15    Fog
7  01-10-2017  mumbai           92          5   Rain

Group: newyork

          day     city  temperature  windspeed  event
0  01-01-2017  newyork           32          6   Rain
1  01-04-2017  newyork           36          7  Sunny
2  01-05-2017  newyork           28         12   Snow
3  01-06-2017  newyork           33          7  Sunny

Group: paris

           day   city  temperature  windspeed   event
8   01-11-2017  paris           45         20   Sunny
9   01-12-2017  paris           50         13  Cloudy
10  01-13-2017  paris           54          8  Cloudy
11  01-14-2017  paris           42         10  Cloudy

In [13]:
gr.get_group('paris')

           day   city  temperature  windspeed   event
8   01-11-2017  paris           45         20   Sunny
9   01-12-2017  paris           50         13  Cloudy
10  01-13-2017  paris           54          8  Cloudy
11  01-14-2017  paris           42         10  Cloudy

In [14]:
gr.min()

                day  temperature  windspeed   event
city
mumbai   01-07-2017           85          5     Fog
newyork  01-01-2017           28          6    Rain
paris    01-11-2017           42          8  Cloudy

In [16]:
gr.get_group('paris').max()

day            01-14-2017
city                paris
temperature            54
windspeed              20
event               Sunny
dtype: object

In [21]:
from IPython.display import display

for j, group in data11.groupby(['city','event']):
    display(group)

          day    city  temperature  windspeed event
5  01-08-2017  mumbai           85         12   Fog
6  01-09-2017  mumbai           87         15   Fog

          day    city  temperature  windspeed event
7  01-10-2017  mumbai           92          5  Rain

          day    city  temperature  windspeed  event
4  01-07-2017  mumbai           90          5  Sunny

          day     city  temperature  windspeed event
0  01-01-2017  newyork           32          6  Rain

          day     city  temperature  windspeed event
2  01-05-2017  newyork           28         12  Snow

          day     city  temperature  windspeed  event
1  01-04-2017  newyork           36          7  Sunny
3  01-06-2017  newyork           33          7  Sunny

           day   city  temperature  windspeed   event
9   01-12-2017  paris           50         13  Cloudy
10  01-13-2017  paris           54          8  Cloudy
11  01-14-2017  paris           42         10  Cloudy

          day   city  temperature  windspeed  event
8  01-11-2017  paris           45         20  Sunny

PIVOT AND PIVOT TABLE

PIVOT

In [25]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data .csv')
data

           day     city  temperature  windspeed   event
0   01-01-2017  newyork           32          6    Rain
1   01-04-2017  newyork           36          7   Sunny
2   01-05-2017  newyork           28         12    Snow
3   01-06-2017  newyork           33          7   Sunny
4   01-07-2017   mumbai           90          5   Sunny
5   01-08-2017   mumbai           85         12     Fog
6   01-09-2017   mumbai           87         15     Fog
7   01-10-2017   mumbai           92          5    Rain
8   01-11-2017    paris           45         20   Sunny
9   01-12-2017    paris           50         13  Cloudy
10  01-13-2017    paris           54          8  Cloudy
11  01-14-2017    paris           42         10  Cloudy

In [26]:
data.pivot(index='day',columns='city')

           temperature               windspeed                event          \
city            mumbai newyork paris    mumbai newyork paris mumbai newyork
day
01-01-2017         NaN    32.0   NaN       NaN     6.0   NaN    NaN    Rain
01-04-2017         NaN    36.0   NaN       NaN     7.0   NaN    NaN   Sunny
01-05-2017         NaN    28.0   NaN       NaN    12.0   NaN    NaN    Snow
01-06-2017         NaN    33.0   NaN       NaN     7.0   NaN    NaN   Sunny
01-07-2017        90.0     NaN   NaN       5.0     NaN   NaN  Sunny     NaN
01-08-2017        85.0     NaN   NaN      12.0     NaN   NaN    Fog     NaN
01-09-2017        87.0     NaN   NaN      15.0     NaN   NaN    Fog     NaN
01-10-2017        92.0     NaN   NaN       5.0     NaN   NaN   Rain     NaN
01-11-2017         NaN     NaN  45.0       NaN     NaN  20.0    NaN     NaN
01-12-2017         NaN     NaN  50.0       NaN     NaN  13.0    NaN     NaN
01-13-2017         NaN     NaN  54.0       NaN     NaN   8.0    NaN     NaN
01-14-2017         NaN     NaN  42.0       NaN     NaN  10.0    NaN     NaN


city         paris
day
01-01-2017     NaN
01-04-2017     NaN
01-05-2017     NaN
01-06-2017     NaN
01-07-2017     NaN
01-08-2017     NaN
01-09-2017     NaN
01-10-2017     NaN
01-11-2017   Sunny
01-12-2017  Cloudy
01-13-2017  Cloudy
01-14-2017  Cloudy

In [27]:
data.pivot(index='day',columns='event')

             city                                    temperature              \
event      Cloudy     Fog     Rain     Snow    Sunny      Cloudy   Fog  Rain
day
01-01-2017    NaN     NaN  newyork      NaN      NaN         NaN   NaN  32.0
01-04-2017    NaN     NaN      NaN      NaN  newyork         NaN   NaN   NaN
01-05-2017    NaN     NaN      NaN  newyork      NaN         NaN   NaN   NaN
01-06-2017    NaN     NaN      NaN      NaN  newyork         NaN   NaN   NaN
01-07-2017    NaN     NaN      NaN      NaN   mumbai         NaN   NaN   NaN
01-08-2017    NaN  mumbai      NaN      NaN      NaN         NaN  85.0   NaN
01-09-2017    NaN  mumbai      NaN      NaN      NaN         NaN  87.0   NaN
01-10-2017    NaN     NaN   mumbai      NaN      NaN         NaN   NaN  92.0
01-11-2017    NaN     NaN      NaN      NaN    paris         NaN   NaN   NaN
01-12-2017  paris     NaN      NaN      NaN      NaN        50.0   NaN   NaN
01-13-2017  paris     NaN      NaN      NaN      NaN        54.0   NaN   NaN
01-14-2017  paris     NaN      NaN      NaN      NaN        42.0   NaN   NaN

                       windspeed
event       Snow Sunny    Cloudy   Fog Rain  Snow Sunny
day
01-01-2017   NaN   NaN       NaN   NaN  6.0   NaN   NaN
01-04-2017   NaN  36.0       NaN   NaN  NaN   NaN   7.0
01-05-2017  28.0   NaN       NaN   NaN  NaN  12.0   NaN
01-06-2017   NaN  33.0       NaN   NaN  NaN   NaN   7.0
01-07-2017   NaN  90.0       NaN   NaN  NaN   NaN   5.0
01-08-2017   NaN   NaN       NaN  12.0  NaN   NaN   NaN
01-09-2017   NaN   NaN       NaN  15.0  NaN   NaN   NaN
01-10-2017   NaN   NaN       NaN   NaN  5.0   NaN   NaN
01-11-2017   NaN  45.0       NaN   NaN  NaN   NaN  20.0
01-12-2017   NaN   NaN      13.0   NaN  NaN   NaN   NaN
01-13-2017   NaN   NaN       8.0   NaN  NaN   NaN   NaN
01-14-2017   NaN   NaN      10.0   NaN  NaN   NaN   NaN

PIVOT TABLE

#IT ALLOWS YOU TO PERFORM COMMON AGGRIGATE STASTICAL CALCULATION (SUM,MEAN,MAX,MIN)

In [28]:
data.pivot_table(index='day',columns='city',values='windspeed')

city        mumbai  newyork  paris
day
01-01-2017     NaN      6.0    NaN
01-04-2017     NaN      7.0    NaN
01-05-2017     NaN     12.0    NaN
01-06-2017     NaN      7.0    NaN
01-07-2017     5.0      NaN    NaN
01-08-2017    12.0      NaN    NaN
01-09-2017    15.0      NaN    NaN
01-10-2017     5.0      NaN    NaN
01-11-2017     NaN      NaN   20.0
01-12-2017     NaN      NaN   13.0
01-13-2017     NaN      NaN    8.0
01-14-2017     NaN      NaN   10.0

In [30]:
data.pivot_table(index='day',columns='city',aggfunc='sum',margins=True)

C:\Users\adith\AppData\Local\Temp\ipykernel_15668\3053186088.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.pivot_table(index='day',columns='city',aggfunc='sum',margins=True)

                      event                                               \
city                 mumbai             newyork                    paris
day
01-01-2017              NaN                Rain                      NaN
01-04-2017              NaN               Sunny                      NaN
01-05-2017              NaN                Snow                      NaN
01-06-2017              NaN               Sunny                      NaN
01-07-2017            Sunny                 NaN                      NaN
01-08-2017              Fog                 NaN                      NaN
01-09-2017              Fog                 NaN                      NaN
01-10-2017             Rain                 NaN                      NaN
01-11-2017              NaN                 NaN                    Sunny
01-12-2017              NaN                 NaN                   Cloudy
01-13-2017              NaN                 NaN                   Cloudy
01-14-2017              NaN                 NaN                   Cloudy
All         SunnyFogFogRain  RainSunnySnowSunny  SunnyCloudyCloudyCloudy

                                                              temperature  \
city                                                      All      mumbai
day
01-01-2017                                               Rain         NaN
01-04-2017                                              Sunny         NaN
01-05-2017                                               Snow         NaN
01-06-2017                                              Sunny         NaN
01-07-2017                                              Sunny        90.0
01-08-2017                                                Fog        85.0
01-09-2017                                                Fog        87.0
01-10-2017                                               Rain        92.0
01-11-2017                                              Sunny         NaN
01-12-2017                                             Cloudy         NaN
01-13-2017                                             Cloudy         NaN
01-14-2017                                             Cloudy         NaN
All         RainSunnySnowSunnySunnyFogFogRainSunnyCloudyCl...         354

                              windspeed
city       newyork paris  All    mumbai newyork paris  All
day
01-01-2017    32.0   NaN   32       NaN     6.0   NaN    6
01-04-2017    36.0   NaN   36       NaN     7.0   NaN    7
01-05-2017    28.0   NaN   28       NaN    12.0   NaN   12
01-06-2017    33.0   NaN   33       NaN     7.0   NaN    7
01-07-2017     NaN   NaN   90       5.0     NaN   NaN    5
01-08-2017     NaN   NaN   85      12.0     NaN   NaN   12
01-09-2017     NaN   NaN   87      15.0     NaN   NaN   15
01-10-2017     NaN   NaN   92       5.0     NaN   NaN    5
01-11-2017     NaN  45.0   45       NaN     NaN  20.0   20
01-12-2017     NaN  50.0   50       NaN     NaN  13.0   13
01-13-2017     NaN  54.0   54       NaN     NaN   8.0    8
01-14-2017     NaN  42.0   42       NaN     NaN  10.0   10
All            129   191  674        37      32    51  120

CONCATINATION

In [38]:
tcs={'id':[101,102,103,104],
'name':['max','Dipin', 'Jose','rahul'],
}
wipro={'id': [101,102, 103,104],
'name': ['Dev', 'Sreenath', 'Sreerag', 'Shafeel'],
'age': [24, 24, 27, 26]
}

In [39]:
a=pd.DataFrame(tcs)
a

b=pd.DataFrame(wipro)
b

pd.concat([a,b])  #JOIN TWO DATAFRAMES

    id      name   age
0  101       max   NaN
1  102     Dipin   NaN
2  103      Jose   NaN
3  104     rahul   NaN
0  101       Dev  24.0
1  102  Sreenath  24.0
2  103   Sreerag  27.0
3  104   Shafeel  26.0

In [ ]:
pd.concat([a,b],ignore_index=True)

#get common index after concatination

    id      name   age
0  101       max   NaN
1  102     Dipin   NaN
2  103      Jose   NaN
3  104     rahul   NaN
4  101       Dev  24.0
5  102  Sreenath  24.0
6  103   Sreerag  27.0
7  104   Shafeel  26.0

In [ ]:
pd.concat([a,b],keys=['tcs','wipro'])
#vertically arraging

          id      name   age
tcs   0  101       max   NaN
      1  102     Dipin   NaN
      2  103      Jose   NaN
      3  104     rahul   NaN
wipro 0  101       Dev  24.0
      1  102  Sreenath  24.0
      2  103   Sreerag  27.0
      3  104   Shafeel  26.0

In [ ]:
pd.concat([a,b],axis=1)

#horizontly arranging

    id   name   id      name  age
0  101    max  101       Dev   24
1  102  Dipin  102  Sreenath   24
2  103   Jose  103   Sreerag   27
3  104  rahul  104   Shafeel   26

In [ ]:
salary=pd.Series([65000,75000,15000,25000],name='salary')
pd.concat([a,salary],axis=1)

#concatae dataframe with series

    id   name  salary
0  101    max   65000
1  102  Dipin   75000
2  103   Jose   15000
3  104  rahul   25000

MERGE()

#COMMON COLUMN NEEDED LEFT JOIN,RIGHT FULL APPLICABLE

In [ ]:
tcs={'id':[101,102,103,106],
'name':['max','Dipin', 'Jose','rahul'],
}
wipro={'id': [101,102, 103,105],
'name': ['Dev', 'Sreenath', 'Sreerag', 'Shafeel'],
'age': [24, 24, 27, 26]
}

a=pd.DataFrame(tcs)
a

    id   name
0  101    max
1  102  Dipin
2  103   Jose
3  106  rahul

In [48]:
b=pd.DataFrame(wipro)
b

    id      name  age
0  101       Dev   24
1  102  Sreenath   24
2  103   Sreerag   27
3  105   Shafeel   26

In [45]:
pd.merge(a,b,on='id')

    id name_x    name_y  age
0  101    max       Dev   24
1  102  Dipin  Sreenath   24
2  103   Jose   Sreerag   27

In [46]:
pd.merge(a,b,on='id',suffixes=['_tcs','_wipro'])

    id name_tcs name_wipro  age
0  101      max        Dev   24
1  102    Dipin   Sreenath   24
2  103     Jose    Sreerag   27

In [49]:
pd.merge(a,b,on='id',how='outer')  #how='inner' by default

    id name_x    name_y   age
0  101    max       Dev  24.0
1  102  Dipin  Sreenath  24.0
2  103   Jose   Sreerag  27.0
3  105    NaN   Shafeel  26.0
4  106  rahul       NaN   NaN

In [50]:
pd.merge(a,b,on='id',how='left')

    id name_x    name_y   age
0  101    max       Dev  24.0
1  102  Dipin  Sreenath  24.0
2  103   Jose   Sreerag  27.0
3  106  rahul       NaN   NaN

In [52]:
pd.merge(a,b,on='id',how='right')

    id name_x    name_y  age
0  101    max       Dev   24
1  102  Dipin  Sreenath   24
2  103   Jose   Sreerag   27
3  105    NaN   Shafeel   26

In [ ]:
pd.merge(a,b,on='id',how='outer',indicator=True)

#from where or which table merge happnes

    id name_x    name_y   age      _merge
0  101    max       Dev  24.0        both
1  102  Dipin  Sreenath  24.0        both
2  103   Jose   Sreerag  27.0        both
3  105    NaN   Shafeel  26.0  right_only
4  106  rahul       NaN   NaN   left_only

MELT

USED TO UNPIVOT THE DATA,CAHNGE THE DATAFRAME FORMAT FROM WIDE(MANY) COLOUMS TO LONG (MORE ROWS)

In [3]:
data=pd.read_csv("C:\\Users\\adith\\python practice\\numpy\\weather_data .csv")
data

           day     city  temperature  windspeed   event
0   01-01-2017  newyork           32          6    Rain
1   01-04-2017  newyork           36          7   Sunny
2   01-05-2017  newyork           28         12    Snow
3   01-06-2017  newyork           33          7   Sunny
4   01-07-2017   mumbai           90          5   Sunny
5   01-08-2017   mumbai           85         12     Fog
6   01-09-2017   mumbai           87         15     Fog
7   01-10-2017   mumbai           92          5    Rain
8   01-11-2017    paris           45         20   Sunny
9   01-12-2017    paris           50         13  Cloudy
10  01-13-2017    paris           54          8  Cloudy
11  01-14-2017    paris           42         10  Cloudy

In [ ]:
pd.melt(data)

#variable- this column contains the name of the orginal column that were melted
#values- this column contain acutual data values from the orginal dataframe

       variable       value
0           day  01-01-2017
1           day  01-04-2017
2           day  01-05-2017
3           day  01-06-2017
4           day  01-07-2017
5           day  01-08-2017
6           day  01-09-2017
7           day  01-10-2017
8           day  01-11-2017
9           day  01-12-2017
10          day  01-13-2017
11          day  01-14-2017
12         city     newyork
13         city     newyork
14         city     newyork
15         city     newyork
16         city      mumbai
17         city      mumbai
18         city      mumbai
19         city      mumbai
20         city       paris
21         city       paris
22         city       paris
23         city       paris
24  temperature          32
25  temperature          36
26  temperature          28
27  temperature          33
28  temperature          90
29  temperature          85
30  temperature          87
31  temperature          92
32  temperature          45
33  temperature          50
34  temperature          54
35  temperature          42
36    windspeed           6
37    windspeed           7
38    windspeed          12
39    windspeed           7
40    windspeed           5
41    windspeed          12
42    windspeed          15
43    windspeed           5
44    windspeed          20
45    windspeed          13
46    windspeed           8
47    windspeed          10
48        event        Rain
49        event       Sunny
50        event        Snow
51        event       Sunny
52        event       Sunny
53        event         Fog
54        event         Fog
55        event        Rain
56        event       Sunny
57        event      Cloudy
58        event      Cloudy
59        event      Cloudy

In [ ]:
pd.melt(data,id_vars='day')

#id vars- the column should remains as an identifier var,it will not be melted
#the day column remain unchanged and is seprated

           day     variable    value
0   01-01-2017         city  newyork
1   01-04-2017         city  newyork
2   01-05-2017         city  newyork
3   01-06-2017         city  newyork
4   01-07-2017         city   mumbai
5   01-08-2017         city   mumbai
6   01-09-2017         city   mumbai
7   01-10-2017         city   mumbai
8   01-11-2017         city    paris
9   01-12-2017         city    paris
10  01-13-2017         city    paris
11  01-14-2017         city    paris
12  01-01-2017  temperature       32
13  01-04-2017  temperature       36
14  01-05-2017  temperature       28
15  01-06-2017  temperature       33
16  01-07-2017  temperature       90
17  01-08-2017  temperature       85
18  01-09-2017  temperature       87
19  01-10-2017  temperature       92
20  01-11-2017  temperature       45
21  01-12-2017  temperature       50
22  01-13-2017  temperature       54
23  01-14-2017  temperature       42
24  01-01-2017    windspeed        6
25  01-04-2017    windspeed        7
26  01-05-2017    windspeed       12
27  01-06-2017    windspeed        7
28  01-07-2017    windspeed        5
29  01-08-2017    windspeed       12
30  01-09-2017    windspeed       15
31  01-10-2017    windspeed        5
32  01-11-2017    windspeed       20
33  01-12-2017    windspeed       13
34  01-13-2017    windspeed        8
35  01-14-2017    windspeed       10
36  01-01-2017        event     Rain
37  01-04-2017        event    Sunny
38  01-05-2017        event     Snow
39  01-06-2017        event    Sunny
40  01-07-2017        event    Sunny
41  01-08-2017        event      Fog
42  01-09-2017        event      Fog
43  01-10-2017        event     Rain
44  01-11-2017        event    Sunny
45  01-12-2017        event   Cloudy
46  01-13-2017        event   Cloudy
47  01-14-2017        event   Cloudy

In [6]:
pd.melt(data,id_vars='city')

       city     variable       value
0   newyork          day  01-01-2017
1   newyork          day  01-04-2017
2   newyork          day  01-05-2017
3   newyork          day  01-06-2017
4    mumbai          day  01-07-2017
5    mumbai          day  01-08-2017
6    mumbai          day  01-09-2017
7    mumbai          day  01-10-2017
8     paris          day  01-11-2017
9     paris          day  01-12-2017
10    paris          day  01-13-2017
11    paris          day  01-14-2017
12  newyork  temperature          32
13  newyork  temperature          36
14  newyork  temperature          28
15  newyork  temperature          33
16   mumbai  temperature          90
17   mumbai  temperature          85
18   mumbai  temperature          87
19   mumbai  temperature          92
20    paris  temperature          45
21    paris  temperature          50
22    paris  temperature          54
23    paris  temperature          42
24  newyork    windspeed           6
25  newyork    windspeed           7
26  newyork    windspeed          12
27  newyork    windspeed           7
28   mumbai    windspeed           5
29   mumbai    windspeed          12
30   mumbai    windspeed          15
31   mumbai    windspeed           5
32    paris    windspeed          20
33    paris    windspeed          13
34    paris    windspeed           8
35    paris    windspeed          10
36  newyork        event        Rain
37  newyork        event       Sunny
38  newyork        event        Snow
39  newyork        event       Sunny
40   mumbai        event       Sunny
41   mumbai        event         Fog
42   mumbai        event         Fog
43   mumbai        event        Rain
44    paris        event       Sunny
45    paris        event      Cloudy
46    paris        event      Cloudy
47    paris        event      Cloudy

In [7]:
pd.melt(data,id_vars='city',var_name='x',value_name='y')

       city            x           y
0   newyork          day  01-01-2017
1   newyork          day  01-04-2017
2   newyork          day  01-05-2017
3   newyork          day  01-06-2017
4    mumbai          day  01-07-2017
5    mumbai          day  01-08-2017
6    mumbai          day  01-09-2017
7    mumbai          day  01-10-2017
8     paris          day  01-11-2017
9     paris          day  01-12-2017
10    paris          day  01-13-2017
11    paris          day  01-14-2017
12  newyork  temperature          32
13  newyork  temperature          36
14  newyork  temperature          28
15  newyork  temperature          33
16   mumbai  temperature          90
17   mumbai  temperature          85
18   mumbai  temperature          87
19   mumbai  temperature          92
20    paris  temperature          45
21    paris  temperature          50
22    paris  temperature          54
23    paris  temperature          42
24  newyork    windspeed           6
25  newyork    windspeed           7
26  newyork    windspeed          12
27  newyork    windspeed           7
28   mumbai    windspeed           5
29   mumbai    windspeed          12
30   mumbai    windspeed          15
31   mumbai    windspeed           5
32    paris    windspeed          20
33    paris    windspeed          13
34    paris    windspeed           8
35    paris    windspeed          10
36  newyork        event        Rain
37  newyork        event       Sunny
38  newyork        event        Snow
39  newyork        event       Sunny
40   mumbai        event       Sunny
41   mumbai        event         Fog
42   mumbai        event         Fog
43   mumbai        event        Rain
44    paris        event       Sunny
45    paris        event      Cloudy
46    paris        event      Cloudy
47    paris        event      Cloudy

CROSS TABLE OR CONTIGENCY TABLE

DISPLAY TEH FREQUENCY DISTRIBUTION OF VARIABLE

In [ ]:
data={'gender':['male','female','female','male','male'],
      'handedness':['right-handed','left-handed','right-handed','right-handed','left-handed']
      
    }
#creating cross tabulation
df=pd.DataFrame(data)
crosstab=pd.crosstab(df['gender'],df['handedness'])
crosstab
#it takes a two columns on the data frame df- gender and handedness.the function count the occurance
#the table shows the count of each combination of gender and handedness.

handedness  left-handed  right-handed
gender
female                1             1
male                  1             2

MAP

ITS IS A PYTHON BUILT IN FUNCTION USED TO APPLY FUNCTION  ON EACH ELEMENT OF A SEQUENCE
ITS CAN BE USED ON PANDAS DATFRAME ALSO

TEH map() function for a dtaframe applies a function element wise to each value in the dataframe

In [3]:
data=pd.read_csv('C:\\Users\\adith\\python practice\\numpy\\weather_data .csv')
data

           day     city  temperature  windspeed   event
0   01-01-2017  newyork           32          6    Rain
1   01-04-2017  newyork           36          7   Sunny
2   01-05-2017  newyork           28         12    Snow
3   01-06-2017  newyork           33          7   Sunny
4   01-07-2017   mumbai           90          5   Sunny
5   01-08-2017   mumbai           85         12     Fog
6   01-09-2017   mumbai           87         15     Fog
7   01-10-2017   mumbai           92          5    Rain
8   01-11-2017    paris           45         20   Sunny
9   01-12-2017    paris           50         13  Cloudy
10  01-13-2017    paris           54          8  Cloudy
11  01-14-2017    paris           42         10  Cloudy

In [ ]:
def square(x):
    return x**2


#my_list=[2,5,8,9]
#list(map(square,my_list))

[4, 25, 64, 81]

In [ ]:
#cant be applied to multiple columns simultaneosly
data['temperature'].map(square)

0     1024
1     1296
2      784
3     1089
4     8100
5     7225
6     7569
7     8464
8     2025
9     2500
10    2916
11    1764
Name: temperature, dtype: int64

In [11]:
data_copy=data.copy()
data_copy['new_temeparture']=data['temperature'].map(square)
data_copy

           day     city  temperature  windspeed   event  new_temeparture
0   01-01-2017  newyork           32          6    Rain             1024
1   01-04-2017  newyork           36          7   Sunny             1296
2   01-05-2017  newyork           28         12    Snow              784
3   01-06-2017  newyork           33          7   Sunny             1089
4   01-07-2017   mumbai           90          5   Sunny             8100
5   01-08-2017   mumbai           85         12     Fog             7225
6   01-09-2017   mumbai           87         15     Fog             7569
7   01-10-2017   mumbai           92          5    Rain             8464
8   01-11-2017    paris           45         20   Sunny             2025
9   01-12-2017    paris           50         13  Cloudy             2500
10  01-13-2017    paris           54          8  Cloudy             2916
11  01-14-2017    paris           42         10  Cloudy             1764

In [13]:
#for handling multiple colums simultanesly

data[['temperature','windspeed']].map(square)

    temperature  windspeed
0          1024         36
1          1296         49
2           784        144
3          1089         49
4          8100         25
5          7225        144
6          7569        225
7          8464         25
8          2025        400
9          2500        169
10         2916         64
11         1764        100