## Overfitting and Underfitting:-
Overfitting and underfitting are two common problems in machine learning that affect how well a model predicts new data.

### 1. Underfitting -
   A model is underfitting when it is too simple to learn the patterns in the training data.
   (മോഡൽ ഡാറ്റയിലെ യഥാർത്ഥ പാറ്റേൺ ശരിയായി പഠിക്കാത്ത അവസ്ഥയാണ്).

Characteristics:
- High training error ❌
- High testing error ❌
- Poor accuracy on both training and new data

Example:
Suppose you want to predict students' marks based on hours studied.

Actual data:
Hours Marks
  1     20
  2     40
  3     60
  4     80
  5     100

If your model predicts:

Marks = 50
for every student, it ignores the relationship between study hours and marks. This is underfitting.

Causes:
- Model is too simple.
- Too few features.
- Training for too few epochs (in neural networks).
- Too much regularization.
 
How to Fix:
- Use a more complex model.
- Add useful features.
- Train longer.
- Reduce regularization.

ലക്ഷണങ്ങൾ:
- ട്രെയിനിംഗ് ഡാറ്റയിലും മോശം പ്രകടനം.
- പുതിയ ഡാറ്റയിലും മോശം പ്രകടനം.
- മോഡൽ വളരെ ലളിതമാണ് (Too Simple).

ഓർക്കാൻ-
"പഠിക്കേണ്ടത് പോലും ശരിയായി പഠിച്ചില്ല."


### 2. Overfitting -
A model is overfitting when it learns the training data too well, including random noise and outliers.
(മോഡൽ ട്രെയിനിംഗ് ഡാറ്റയിലെ എല്ലാ വിവരങ്ങളും, അതിലെ ചെറിയ പിശകുകളും (Noise) വരെ മനപ്പാഠമാക്കുന്ന അവസ്ഥയാണ് Overfitting.)

ഉദാഹരണം

ഒരു വിദ്യാർത്ഥി കഴിഞ്ഞ വർഷത്തെ ചോദ്യപേപ്പർ മാത്രം മനപ്പാഠമാക്കുന്നു.

Practice Test → 100%
Final Exam → 50%

കാരണം പുതിയ ചോദ്യങ്ങൾക്ക് ഉത്തരം പറയാൻ കഴിയുന്നില്ല.
It memorizes instead of learning the general pattern.

Characteristics:
- Very low training error ✅
- High testing error ❌
- Poor performance on unseen data

Causes:
- Model is too complex.
- Too many features.
- Small training dataset.
- Training for too many epochs.
- No regularization.
 
How to Fix:
- Collect more data.
- Use regularization (L1, L2).
- Use dropout (for neural networks).
- Early stopping.
- Simplify the model.
- Remove irrelevant features.

ലക്ഷണങ്ങൾ:
- Training Accuracy വളരെ കൂടുതലാണ്.
- Testing Accuracy കുറവാണ്.
- പുതിയ ഡാറ്റയിൽ ശരിയായി പ്രവചിക്കാൻ കഴിയില്ല.

ഓർക്കാൻ-
"മനസ്സിലാക്കിയില്ല, മനപ്പാഠമാക്കി."


#### Real-Life Example:-

Imagine you're preparing for an exam.

-> Underfitting

You study only one chapter.

Training (practice): Poor
Final exam: Poor

-> Good Fit

You understand all important concepts.

Practice: Good
Final exam: Good

-> Overfitting

You memorize every practice question and answer.

Practice: 100%
Final exam: Poor if questions are different

You memorized instead of understanding.

* Underfitting = Doesn't learn enough.
Think: "Too simple to understand the data."
(കുറച്ച് പഠിച്ചു)
➡️ "പാഠം മുഴുവൻ പഠിച്ചില്ല."



* Overfitting = Learns too much (including noise).
Think: "Memorizes the training data instead of understanding it."
(മനപ്പാഠമാക്കി)
➡️ "അർത്ഥം മനസ്സിലാക്കാതെ എല്ലാം ഓർത്തുവച്ചു."
- ആവശ്യമുള്ളതും ആവശ്യമില്ലാത്തതും എല്ലാം പഠിക്കുന്നു.

 

* Good fit = Learns just the right amount.
Think: "Understands the pattern and predicts well on new data."
(ശരിയായ രീതിയിൽ പഠിപ്പിക്കൽ)
➡️ "പ്രധാനപ്പെട്ടത് മാത്രം പഠിക്കൂ; അനാവശ്യ വിവരങ്ങൾ ഒഴിവാക്കൂ."
Regularization:- ആവശ്യമായത് മാത്രം പഠിക്കാൻ മോഡലിനെ നിയന്ത്രിക്കുന്ന സാങ്കേതിക വിദ്യ.

## Regularization

Regularization is a set of techniques in machine learning that reduces overfitting by discouraging a model from becoming overly complex. The goal is to help the model perform well not only on the training data but also on new, unseen data.

Overfitting ഒഴിവാക്കാൻ ഉപയോഗിക്കുന്ന ഒരു സാങ്കേതിക വിദ്യയാണ് Regularization.

ഇത് മോഡലിനോട് പറയുന്നത്:

"അനാവശ്യമായി എല്ലാം പഠിക്കേണ്ട. പ്രധാനപ്പെട്ട കാര്യങ്ങൾ മാത്രം പഠിക്കൂ."

ഒരു യഥാർത്ഥ ഉദാഹരണം:-

ഒരു അധ്യാപകൻ പരീക്ഷയ്ക്ക് 100 ചോദ്യങ്ങൾ കൊടുക്കുന്നു.

-> Underfitting:- വിദ്യാർത്ഥി 10 ചോദ്യങ്ങൾ മാത്രം പഠിച്ചു. പരീക്ഷയിൽ കുറഞ്ഞ മാർക്ക്.

-> Good Fit:- വിദ്യാർത്ഥി പ്രധാനപ്പെട്ട ആശയങ്ങൾ മനസ്സിലാക്കി പഠിച്ചു. പരീക്ഷയിൽ നല്ല മാർക്ക്.

-> Overfitting:- വിദ്യാർത്ഥി 100 ചോദ്യങ്ങളുടെയും ഉത്തരങ്ങൾ മനപ്പാഠമാക്കി. പരീക്ഷയിൽ പുതിയ ചോദ്യങ്ങൾ വന്നപ്പോൾ ഉത്തരം പറയാൻ   കഴിഞ്ഞില്ല.

- Regularization:-
അധ്യാപകൻ പറയുന്നു:

"എല്ലാം മനപ്പാഠമാക്കണ്ട. ആശയം മനസ്സിലാക്കൂ."

അപ്പോൾ വിദ്യാർത്ഥിക്ക് ഏത് ചോദ്യവും വന്നാലും ഉത്തരം പറയാൻ കഴിയും.

Why is regularization needed?

Imagine you're fitting a curve through data points:

- Underfitting: The model is too simple and misses important patterns.
- Good fit: The model captures the underlying trend.
- Overfitting: The model memorizes the training data, including noise, and performs poorly on new data.

Regularization helps move the model from overfitting toward a better balance.

How does it work?

Most regularization methods add a penalty for large or complex model parameters to the loss function.

-> Common types of regularization:-
### 1. L1 Regularization (Lasso)-
. Encourages some weights to become exactly zero.
. Performs feature selection automatically.
. Produces sparse models.

Example: If you have 100 features but only 10 are important, L1 may set the other 90 weights to zero.


### 2. L2 Regularization (Ridge)
. Shrinks weights toward zero but rarely makes them exactly zero.
. Makes the model more stable.
. Most commonly used regularization technique.

-> Machine Learning-ൽ

ഒരു മോഡലിന് 100 Features ഉണ്ടെന്ന് കരുതുക.

Age
Salary
City
Gender
Height
Weight
...

ഇവയിൽ 20 എണ്ണം മാത്രമാണ് പ്രധാനപ്പെട്ടത്.

-> Lasso Regularization (L1)

- പ്രധാനമല്ലാത്ത Features-ന്റെ weight 0 ആക്കും.
- പ്രധാനപ്പെട്ടവ മാത്രം ഉപയോഗിക്കും.

-> Ridge Regularization (L2)

- എല്ലാ Features-ഉം നിലനിർത്തും.
- പക്ഷേ അവയുടെ weights ചെറുതാക്കും.
- ഒരു weight-ഉം സാധാരണയായി 0 ആക്കില്ല.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.metrics import mean_absolute_error,r2_score

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
data=pd.read_csv('homeprice_onehot_ML.csv')
data

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200   61000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9      robbinsville  2600  575000
10     robbinsville  2900  600000
11     robbinsville  3100  620000
12     robbinsville  3600  695000

In [4]:
data.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200   61000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [5]:
data.tail()

            town  area   price
8   west windsor  3600  710000
9   robbinsville  2600  575000
10  robbinsville  2900  600000
11  robbinsville  3100  620000
12  robbinsville  3600  695000

In [6]:
data.isna().sum()

town     0
area     0
price    0
dtype: int64

In [8]:
data.duplicated().sum()

np.int64(0)

In [9]:
data.info

<bound method DataFrame.info of                town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200   61000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9      robbinsville  2600  575000
10     robbinsville  2900  600000
11     robbinsville  3100  620000
12     robbinsville  3600  695000>

In [10]:
data.describe

<bound method NDFrame.describe of                town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200   61000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9      robbinsville  2600  575000
10     robbinsville  2900  600000
11     robbinsville  3100  620000
12     robbinsville  3600  695000>

In [11]:
data.dtypes

town       str
area     int64
price    int64
dtype: object

In [12]:
lb=LabelEncoder()
data['town']=lb.fit_transform(data['town'])
data[['town']]

    town
0      0
1      0
2      0
3      0
4      0
5      2
6      2
7      2
8      2
9      1
10     1
11     1
12     1

In [13]:
x=data.drop('price',axis=1)
x

    town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [14]:
y=data['price']
y

0     550000
1     565000
2      61000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

### LASSO REGRESSION-L1

In [16]:
from sklearn.linear_model import Lasso

In [ ]:
model=Lasso(alpha=2) #create a lasso regression model.regularization stregthen=2,apply a regularization penalty with strength 2
model.fit(x_train,y_train)


#ALpha parameter controls the strength of L1 regularization penalty 
# #smalL alpha-weak regularization, high risk of overfitting, eg: -0.01,0.1
#medium alpha- eg: 1 or 2
#Large alpha- strong regularization eg: 10-100, may under fit the data.

array([616798.16478164, 639097.91503174, 510021.35088092, 446663.55314296])

In [18]:
y_pred=model.predict(x_test)
y_pred

array([616798.16478164, 639097.91503174, 510021.35088092, 446663.55314296])

In [19]:
model.score(x_test,y_test)

-3.5628515102008214

In [21]:
r2=r2_score(y_test,y_pred)
r2

-3.5628515102008214